theme = "modern"
# icons = "awesome5"
# theme = "plain"
icons = "none"

[[block]]
block = "focused_window"
max_width = 50

[[block]]
block = "battery"
format = "B: {percentage} {time}"
full_format = "F: {percentage} {time}"
critical = 10
allow_missing = true
# missing_format = "B: no"
hide_missing = true

[[block]]
block = "sound"
# format = "{volume} {output_description}"
device_kind = "sink"
on_click = "pavucontrol"

[[block]]
block = "sound"
# format = "{volume} {output_description}"
device_kind = "source"
on_click = "pavucontrol"

[[block]]
block = "bluetooth"
mac = "D8:A0:1D:59:5E:C6"
format = "Mic Toggle"
hide_disconnected = true

[[block]]
block = "disk_space"
path = "/"
format = "{icon}  ⁄  {available}"
info_type = "available"
unit = "GB"
interval = 30
warning = 20.0
alert = 10.0

[[block]]
block = "disk_space"
path = "/home"
format = "{icon} ~{available}"
info_type = "available"
unit = "GB"
interval = 30
warning = 20.0
alert = 10.0

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "docker"

[[block]]
block = "networkmanager"
interface_name_exclude = ["br\\-[0-9a-f]{12}", "docker\\d+"]
ap_format = "{ssid} {strength}"
device_format = "{icon}{name}: {ap} {ips}"
on_click = "alacritty -t terminal-floating -e nmtui"

# [[block]]
# block = "speedtest"
# interval = 1800

[[block]]
block = "time"
interval = 1
format = "%a, %d %b - %H:%M:%S"
on_click = "alacritty -t terminal-floating -e bash -c 'cal -3 ; read'"
