# Starship config

format = "$fill\n$all"
command_timeout = 1200
add_newline = true

[character]
success_symbol = "[\\$](green)"
error_symbol = "[\\$](red)"

[status]
disabled = false
format = "[$status]($style) "
style = "red"
# symbol = "[x](bold red) "
# symbol = "[x](red) "
not_executable_symbol = "[!](bold yellow) "
not_found_symbol = "[?](bold yellow) "

[time]
disabled = false

[line_break]
disabled = false

[cmd_duration]
show_notifications = true
min_time_to_notify = 30000

[memory_usage]
disabled = false
threshold = 80
symbol = "󰍛 "    # from Nerd Font Symbols Preset

[directory]
truncation_length = 8
truncate_to_repo = true
read_only = " 󰌾"        # from Nerd Font Symbols Preset
# fish_style_pwd_dir_length = 4

[direnv]
disabled = true

[fill]
symbol = "─"
style = "bold black"

[git_branch]
symbol = " "
truncation_length = 50

[git_commit]
disabled = false

[git_metrics]
disabled = true

[git_status]
conflicted = "X"
# ahead = ""
# behind = ""
diverged = ""
up_to_date = ""
untracked = "."
stashed = ""
modified = "*"
staged = "+"
# renamed = ""
deleted = "x"

[git_state]
disabled = false

[jobs]
symbol = "󰤄"

[package]
# symbol = "@ "
symbol = "󰏗 " # from Nerd Font Symbols Preset

# https://starship.rs/config/#aws
[aws]
# symbol = "  "
disabled = true

[custom.aws_exp]
command = "node $HOME/.dotfiles/starship/aws_exp.js"
# when = "env | grep AWS_CREDENTIAL_EXPIRATION"
when = "env | grep SAML2AWS_PROFILE"
symbol = " "
style = "bold 208"

[custom.github_pr]
command = "bkt --ttl=10m --scope=\"$(git rev-parse --show-toplevel):$(git branch --show-current)\" -- gh pr view --json number --jq '\"PR #\" + (.number | tostring)' 2>/dev/null"
when = "git rev-parse --is-inside-work-tree 2>/dev/null"
format = "[$output](magenta) "
ignore_timeout = true

# Nerd Font Symbols Preset
# https://starship.rs/presets/nerd-font.html#nerd-font-symbols-preset

[buf]
symbol = " "

[c]
symbol = " "

[conda]
symbol = " "

[dart]
symbol = " "

# [directory]
# read_only = " 󰌾"

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[fossil_branch]
symbol = " "

# [git_branch]
# symbol = " "

[golang]
symbol = " "

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = " "

[hg_branch]
symbol = " "

[hostname]
ssh_symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[lua]
symbol = " "

# [memory_usage]
# symbol = "󰍛 "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[os.symbols]
Alpaquita = " "
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = "󰍲 "

# [package]
# symbol = "󰏗 "

[pijul_channel]
symbol = " "

[python]
symbol = " "

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "
