require("options")
-- require("lsp")
-- require("colorscheme")
-- require("functions")
require("autocommands")
-- require("commands")
-- require("plugins")
require("mappings")
-- require("diagnostics")
