" ------ General settings ------

set nocompatible

syntax on
filetype on " enables filetype detection
filetype plugin on " enables filetype specific plugins
let mapleader=" "

set autoread " reload file after changed by running a !command
set backspace=indent,eol,start
set completeopt=menu,preview " show popup menu on completion with extra info
set completefunc=syntaxcomplete#Complete " set user-mode completions for <C-x><C-u>
set cursorline " highlight cursor line
set expandtab " convert tabs to spaces
set formatoptions=cq1tj " formatting
set hidden " hide abandoned buffers
set hlsearch " highlight search results
set incsearch " go to first match when typing
set laststatus=2 " show statusline for single buffer
set lazyredraw " do not redraw screen until needed
set list " display special chars
set listchars=tab:→\ ,trail:∎ " special chars for list mode
set nomodelineexpr  " disable modelinexpr, see: https://github.com/numirias/security/blob/master/doc/2019-06-04_ace-vim-neovim.md
set mouse= " disable mouse
set number " display line numbers
set omnifunc=syntaxcomplete#Complete " enable omnicompletion
set scrolloff=6 " keep 6 lines above/below cursor line
set shiftwidth=0 " use tabstop number of tabs to indent
set showbreak=↪ " mark wrapped lines
set showcmd " show last command on bottom
set showmatch " highlight matching bracket
set splitbelow " open new horizontal splits below
set splitright " open new vertical splits on the right
set tabstop=4 " tab key inserts 4 spaces
set wildmenu " enable filename completion
set wildmode=list:longest,full


" ------ Plugins ------

" install plug.vim
if empty(glob('~/.vim/autoload/plug.vim'))
    silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    autocmd VimEnter * PlugInstall
endif

call plug#begin('~/.vim/plugged')


source $HOME/.dotfiles/vim/plugins.vim
source $HOME/.dotfiles/vim/files.vim
source $HOME/.dotfiles/vim/files-fzf.vim
source $HOME/.dotfiles/vim/dev.vim
source $HOME/.dotfiles/vim/python.vim
source $HOME/.dotfiles/vim/textobj.vim
source $HOME/.dotfiles/vim/vimwiki.vim

call plug#end()

filetype plugin indent on

" ------ Imports ------

" colors
source $HOME/.dotfiles/vim/uolors.vim
" status line
source $HOME/.dotfiles/vim/statusline.vim
" abbrevs
source $HOME/.dotfiles/vim/abbrev.vim


" ------ Mappings ------

" jump between splits
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

" switch between buffers
nnoremap <silent> gB :bp<CR>
nnoremap <silent> gb :bn<CR>

" insert blank lines
nnoremap gO  :<c-u>put! =repeat(nr2char(10), v:count1)<cr>'[
nnoremap go  :<c-u>put =repeat(nr2char(10), v:count1)<cr>

" search for word (like grep -w)
nnoremap <Leader>s /\<\><left><left>

" reselect visual block after (un)indent
vnoremap < <gv
vnoremap > >gv

" select inserted/pasted text
nnoremap gV `[v`]


" change cursor color in insert/normal mode
let &t_SI = "\<Esc>]12;orange\x7"
let &t_EI = "\<Esc>]12;lightblue\x7"
autocmd VimLeave * silent !echo -ne "\033]112\007"


" open images with imv
autocmd BufEnter *.png,*.jpg,*.gif exec "!imv ".expand("%") | :bw


" enable/disable wrap
nnoremap <Leader>w1 :set wrap<CR>
nnoremap <Leader>w0 :set nowrap<CR>


" Use wl-clipboard for copy/paste
" Src: https://www.reddit.com/r/Fedora/comments/ax9p9t/vim_and_system_clipboard_under_wayland/
xnoremap "+y y:call system("wl-copy", @")<cr>
nnoremap "+p :let @"=substitute(system("wl-paste --no-newline"), '<C-v><C-m>', '', 'g')<cr>p
nnoremap "*p :let @"=substitute(system("wl-paste --no-newline --primary"), '<C-v><C-m>', '', 'g')<cr>p
nnoremap <Leader>yy :call system("wl-copy ", getline("."))<CR>
