" ------ General settings ------

set nocompatible

syntax on
filetype on " enables filetype detection
filetype plugin on " enables filetype specific plugins
let mapleader=" "

set autoread " reload file after changed by running a !command
set backspace=indent,eol,start
set completeopt=menu,preview " show popup menu on completion with extra info
set completefunc=syntaxcomplete#Complete " set user-mode completions for <C-x><C-u>
set cursorline " highlight cursor line
set expandtab " convert tabs to spaces
set formatoptions=cq1tj " formatting
set hlsearch " highlight search results
set incsearch " go to first match when typing
set laststatus=2 " show statusline for single buffer
set lazyredraw " do not redraw screen until needed
set list " display special chars
set listchars=tab:→\ ,trail:∎ " special chars for list mode
set nomodelineexpr  " disable modelinexpr, see: https://github.com/numirias/security/blob/master/doc/2019-06-04_ace-vim-neovim.md
set mouse= " disable mouse
set number " display line numbers
set omnifunc=syntaxcomplete#Complete " enable omnicompletion
set scrolloff=6 " keep 6 lines above/below cursor line
set shiftwidth=0 " use tabstop number of tabs to indent
set showbreak=↪ " mark wrapped lines
set showcmd " show last command on bottom
set showmatch " highlight matching bracket
set splitbelow " open new horizontal splits below
set splitright " open new vertical splits on the right
set tabstop=4 " tab key inserts 4 spaces
set wildmenu " enable filename completion
set wildmode=list:longest,full


" ------ Plugins ------

" install plug.vim
if empty(glob('~/.vim/autoload/plug.vim'))
    silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    autocmd VimEnter * PlugInstall
endif

call plug#begin('~/.vim/plugged')

" highlight yanked region
Plug 'machakann/vim-highlightedyank'

" underline word under cursor
Plug 'itchyny/vim-cursorword'
    let g:cursorword_highlight = 0
    " NOTE: colors for CursorWord0 and CursorWord1 are defined in uolors.vim

" Readline style insertion
Plug 'tpope/vim-rsi'

" disables search highlighting when you are done searching and re-enables it when you search again
Plug 'romainl/vim-cool'

" Range, pattern and substitute preview
Plug 'markonm/traces.vim'

" Close brackets on enter
" Config: https://github.com/rstacruz/vim-closer/blob/master/plugin/closer.vim
Plug 'rstacruz/vim-closer'

" Asynchronous build and test dispatcher
Plug 'tpope/vim-dispatch'

" isolate part of a file to create a 'safe edit environment'
Plug 'ferranpm/vim-isolate'

source $HOME/.dotfiles/vim/files.vim
source $HOME/.dotfiles/vim/dev.vim
source $HOME/.dotfiles/vim/python.vim
source $HOME/.dotfiles/vim/textobj.vim

call plug#end()

filetype plugin indent on


" ------ Imports ------

" colors
source $HOME/.dotfiles/vim/uolors.vim
" status line
source $HOME/.dotfiles/vim/statusline.vim
" abbrevs
source $HOME/.dotfiles/vim/abbrev.vim


" ------ Mappings ------

" jump between splits
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

" switch between buffers
nnoremap <silent> gB :bp<CR>
nnoremap <silent> gb :bn<CR>

" insert blank lines
nnoremap gO  :<c-u>put! =repeat(nr2char(10), v:count1)<cr>'[
nnoremap go  :<c-u>put =repeat(nr2char(10), v:count1)<cr>

" search for word (like grep -w)
nnoremap <Leader>s /\<\><left><left>

" reselect visual block after (un)indent
vnoremap < <gv
vnoremap > >gv

" select inserted/pasted text
nnoremap gV `[v`]
