swipe:
  3:
    left:
      sendkey: 'LEFTALT+LEFT'
    right:
      sendkey: 'LEFTALT+RIGHT'
      keypress:
        LEFTCTRL:
          sendkey: 'LEFTCTRL+T'
    up:
      sendkey: 'LEFTCTRL+LEFTSHIFT+TAB'
      keypress:
        LEFTCTRL:
          sendkey: 'LEFTCTRL+R'
    down:
      sendkey: 'LEFTCTRL+TAB'
      keypress:
        LEFTCTRL:
          sendkey: 'LEFTCTRL+R'
  4:
    left:
      sendkey: 'LEFTMETA+H'
      keypress:
        LEFTCTRL:
          command: 'swaymsg focus output left'
    right:
      sendkey: 'LEFTMETA+L'
      keypress:
        LEFTCTRL:
          command: 'swaymsg focus output right'
    up:
      sendkey: 'LEFTMETA+K'
      keypress:
        LEFTCTRL:
          command: 'swaymsg focus output up'
    down:
      sendkey: 'LEFTMETA+J'
      keypress:
        LEFTCTRL:
          command: 'swaymsg focus output down'

rotate:
  # 2:
  2:
    counterclockwise:
      sendkey: 'LEFTMETA+ESC'
    clockwise:
      sendkey: 'LEFTMETA+TAB'
  3:
    counterclockwise:
      sendkey: 'LEFTCTRL+W'
      keypress:
        LEFTCTRL:
          sendkey: 'LEFTCTRL+LEFTSHIFT+T'
    clockwise:
      sendkey: 'LEFTCTRL+T'
      keypress:
        LEFTCTRL:
          sendkey: 'LEFTCTRL+R'

pinch:
  # 2:
  # 3:
  #   out:
  #   in:
  # 4:


threshold:
  swipe: 0.6
  pinch: 0.5

interval:
  # swipe: 0.5
  pinch: 0.4

plugin:
  inputs:
    libinput_command_input:
      show-keycodes: true
