#
# ~/.bash_profile
#

export BASH_SILENCE_DEPRECATION_WARNING=1
export NPM_TOKEN="$(cat "$HOME/.secrets/LEGO_GH_TOKEN")"
export NODE_AUTH_TOKEN="$(cat "$HOME/.secrets/LEGO_GH_TOKEN")"

[[ -f ~/.bashrc ]] && . ~/.bashrc

test -e "${HOME}/.iterm2_shell_integration.bash" && source "${HOME}/.iterm2_shell_integration.bash" || true
. "$HOME/.cargo/env"
