#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

export PATH="$HOME/.dotfiles/bin:$HOME/.local/bin:/opt/homebrew/bin:$PATH"

CONFIG=$HOME/.dotfiles/bash/config

# core
source $CONFIG/colors
source $CONFIG/text
source $CONFIG/search
source $CONFIG/shell
source $CONFIG/completion
source $CONFIG/misc

# programs
source $CONFIG/fzf
source $CONFIG/git
source $CONFIG/asdf
source $CONFIG/python
source $CONFIG/node
source $CONFIG/aws
source $CONFIG/zk
source $CONFIG/docker
# source $CONFIG/platformio
# source $CONFIG/terraform

eval "$(starship init bash)"
eval "$(zoxide init bash)"
eval "$(direnv hook bash)"
eval "$(gh completion -s bash)"
