#
# ~/.bash_profile
#

export BASH_SILENCE_DEPRECATION_WARNING=1

if [[ ${LC_ALL-} == "C.UTF-8" ]]; then
  unset LC_ALL
fi

[[ -f ~/.bashrc ]] && . ~/.bashrc
[[ -f "/Users/tomek/.local/share/bob/env/env.sh" ]] && . "/Users/tomek/.local/share/bob/env/env.sh"
